In [1]:
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
import cv2 
import os 
import glob 
img_dir1 = r"E:\Amir" # Enter Directory of all images 
data_path1 = os.path.join(img_dir1,'*jfif') 
files1 = glob.glob(data_path1)  
data1 = []
for j in files1: 
    img = cv2.imread(j)
    img.resize((28,28))
    data1.append(img) 

In [3]:
x1=np.array(data1)

In [4]:
img_dir2 = r"E:\Data"
data_path2 = os.path.join(img_dir2,'*jfif') 
files2 = glob.glob(data_path2) 
data2 = []
for i in files2: 
    img1 = cv2.imread(i) 
    img1.resize((28,28))
    data2.append(img1) 

In [5]:
x2=np.array(data2)

In [6]:
y1=np.zeros(20)
y1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
y2=np.ones(20)
y2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [8]:
data1[1].shape

(28, 28)

In [9]:
y=np.concatenate((y1,y2),axis=0)
print(y.shape)

x=np.concatenate((x1,x2),axis=0)
print(x.shape)

(40,)
(40, 28, 28)


In [87]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.1, random_state = 10,shuffle=True)

In [88]:
x_train.shape

(36, 28, 28)

In [89]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,Dense,MaxPooling2D,Flatten


In [102]:
model = Sequential()

model.add(Conv2D(32, (3,3) , input_shape = (28,28,1)))     #Input Layer
model.add(MaxPooling2D(2,2))
          
model.add(Conv2D(16, (3,3) , activation='relu'))      #Hidden Layer
model.add(MaxPooling2D(2,2))   

model.add(Conv2D(8, (3,3) , activation='relu'))       #Hidden Layer
model.add(MaxPooling2D(2,2))

model.add(Flatten())

model.add(Dense(4, activation = 'relu')) 

model.add(Dense(1, activation = 'sigmoid'))  #Output Layer

model.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics = ['accuracy'])

model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_52 (Conv2D)          (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_51 (MaxPoolin  (None, 13, 13, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_53 (Conv2D)          (None, 11, 11, 16)        4624      
                                                                 
 max_pooling2d_52 (MaxPoolin  (None, 5, 5, 16)         0         
 g2D)                                                            
                                                                 
 conv2d_54 (Conv2D)          (None, 3, 3, 8)           1160      
                                                                 
 max_pooling2d_53 (MaxPoolin  (None, 1, 1, 8)        

In [103]:
history = model.fit(x_train , y_train , validation_split=(0.1) , epochs=50)

Epoch 1/50
1/1 [==============================] - 3s 3s/step - loss: 1.0228 - accuracy: 0.5625 - val_loss: 1.2936 - val_accuracy: 0.2500
Epoch 2/50
1/1 [==============================] - 0s 164ms/step - loss: 1.0774 - accuracy: 0.5000 - val_loss: 0.6803 - val_accuracy: 0.7500
Epoch 3/50
1/1 [==============================] - 0s 157ms/step - loss: 0.6882 - accuracy: 0.4688 - val_loss: 0.6488 - val_accuracy: 0.7500
Epoch 4/50
1/1 [==============================] - 0s 179ms/step - loss: 0.6735 - accuracy: 0.5000 - val_loss: 0.7541 - val_accuracy: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 171ms/step - loss: 0.6214 - accuracy: 0.7188 - val_loss: 2.2750 - val_accuracy: 0.2500
Epoch 6/50
1/1 [==============================] - 0s 167ms/step - loss: 0.7482 - accuracy: 0.6875 - val_loss: 1.5296 - val_accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 154ms/step - loss: 0.6710 - accuracy: 0.6875 - val_loss: 0.6454 - val_accuracy: 0.7500
Epoch 8/50
1/1 [=======

In [104]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 83ms/step - loss: 0.6820 - accuracy: 0.7500


[0.6820436716079712, 0.75]

In [105]:
predictions = np.argmax(model.predict(x_test),axis = 1)
predictions

1/1 [==============================] - 0s 264ms/step


array([0, 0, 0, 0], dtype=int64)

In [106]:
from sklearn.metrics import accuracy_score,confusion_matrix ,classification_report
cm=confusion_matrix(y_test,predictions)
print(cm)
print(accuracy_score(y_test,predictions))

[[1 0]
 [3 0]]
0.25
